# Generated by Django 3.2.5 on 2021-12-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphotos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
