# Generated by Django 3.2.5 on 2021-12-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphotos', '0003_alter_photo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
