# Generated by Django 3.2.5 on 2022-01-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myphotos', '0007_photo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
    ]
